# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import tushare_pb2 as tushare__pb2


class TushareServiceStub(object):
  """Interface exported by the server.
  """

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.MoneySupply = channel.unary_unary(
        '/routeguide.TushareService/MoneySupply',
        request_serializer=tushare__pb2.EmptyParam.SerializeToString,
        response_deserializer=tushare__pb2.Dataframe.FromString,
        )
    self.HistData = channel.unary_unary(
        '/routeguide.TushareService/HistData',
        request_serializer=tushare__pb2.HistDataRequest.SerializeToString,
        response_deserializer=tushare__pb2.Dataframe.FromString,
        )
    self.TickData = channel.unary_unary(
        '/routeguide.TushareService/TickData',
        request_serializer=tushare__pb2.TickDataRequest.SerializeToString,
        response_deserializer=tushare__pb2.Dataframe.FromString,
        )
    self.StockBasics = channel.unary_unary(
        '/routeguide.TushareService/StockBasics',
        request_serializer=tushare__pb2.EmptyParam.SerializeToString,
        response_deserializer=tushare__pb2.Dataframe.FromString,
        )
    self.TodayAll = channel.unary_unary(
        '/routeguide.TushareService/TodayAll',
        request_serializer=tushare__pb2.EmptyParam.SerializeToString,
        response_deserializer=tushare__pb2.Dataframe.FromString,
        )
    self.TodayTicks = channel.unary_unary(
        '/routeguide.TushareService/TodayTicks',
        request_serializer=tushare__pb2.TodayTicksRequest.SerializeToString,
        response_deserializer=tushare__pb2.Dataframe.FromString,
        )
    self.Index = channel.unary_unary(
        '/routeguide.TushareService/Index',
        request_serializer=tushare__pb2.EmptyParam.SerializeToString,
        response_deserializer=tushare__pb2.Dataframe.FromString,
        )


class TushareServiceServicer(object):
  """Interface exported by the server.
  """

  def MoneySupply(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def HistData(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def TickData(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def StockBasics(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def TodayAll(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def TodayTicks(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def Index(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_TushareServiceServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'MoneySupply': grpc.unary_unary_rpc_method_handler(
          servicer.MoneySupply,
          request_deserializer=tushare__pb2.EmptyParam.FromString,
          response_serializer=tushare__pb2.Dataframe.SerializeToString,
      ),
      'HistData': grpc.unary_unary_rpc_method_handler(
          servicer.HistData,
          request_deserializer=tushare__pb2.HistDataRequest.FromString,
          response_serializer=tushare__pb2.Dataframe.SerializeToString,
      ),
      'TickData': grpc.unary_unary_rpc_method_handler(
          servicer.TickData,
          request_deserializer=tushare__pb2.TickDataRequest.FromString,
          response_serializer=tushare__pb2.Dataframe.SerializeToString,
      ),
      'StockBasics': grpc.unary_unary_rpc_method_handler(
          servicer.StockBasics,
          request_deserializer=tushare__pb2.EmptyParam.FromString,
          response_serializer=tushare__pb2.Dataframe.SerializeToString,
      ),
      'TodayAll': grpc.unary_unary_rpc_method_handler(
          servicer.TodayAll,
          request_deserializer=tushare__pb2.EmptyParam.FromString,
          response_serializer=tushare__pb2.Dataframe.SerializeToString,
      ),
      'TodayTicks': grpc.unary_unary_rpc_method_handler(
          servicer.TodayTicks,
          request_deserializer=tushare__pb2.TodayTicksRequest.FromString,
          response_serializer=tushare__pb2.Dataframe.SerializeToString,
      ),
      'Index': grpc.unary_unary_rpc_method_handler(
          servicer.Index,
          request_deserializer=tushare__pb2.EmptyParam.FromString,
          response_serializer=tushare__pb2.Dataframe.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'routeguide.TushareService', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
