# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: tushare.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='tushare.proto',
  package='routeguide',
  syntax='proto3',
  serialized_options=_b('\n\030cn.pxsdirac.grpc.tushareB\016TushareServiceP\001\242\002\003RTG'),
  serialized_pb=_b('\n\rtushare.proto\x12\nrouteguide\"!\n\x11TodayTicksRequest\x12\x0c\n\x04\x63ode\x18\x01 \x01(\t\"\x0c\n\nEmptyParam\"\x1c\n\x0bStringValue\x12\r\n\x05value\x18\x01 \x01(\t\"\x81\x01\n\x0fHistDataRequest\x12\x0c\n\x04\x63ode\x18\x01 \x01(\t\x12\x1f\n\x05start\x18\x02 \x01(\x0b\x32\x10.routeguide.Date\x12\x1d\n\x03\x65nd\x18\x03 \x01(\x0b\x32\x10.routeguide.Date\x12 \n\x05kType\x18\x04 \x01(\x0e\x32\x11.routeguide.KType\"?\n\x0fTickDataRequest\x12\x0c\n\x04\x63ode\x18\x01 \x01(\t\x12\x1e\n\x04\x64\x61te\x18\x02 \x01(\x0b\x32\x10.routeguide.Date\"\x19\n\tDataframe\x12\x0c\n\x04json\x18\x01 \x01(\t\"0\n\x04\x44\x61te\x12\x0c\n\x04year\x18\x01 \x01(\x05\x12\r\n\x05month\x18\x02 \x01(\x05\x12\x0b\n\x03\x64\x61y\x18\x03 \x01(\x05*?\n\x05KType\x12\x05\n\x01\x44\x10\x00\x12\x05\n\x01W\x10\x01\x12\x05\n\x01M\x10\x02\x12\x06\n\x02m5\x10\x03\x12\x07\n\x03m15\x10\x04\x12\x07\n\x03m30\x10\x05\x12\x07\n\x03m60\x10\x06\x32\xd1\x03\n\x0eTushareService\x12>\n\x0bMoneySupply\x12\x16.routeguide.EmptyParam\x1a\x15.routeguide.Dataframe\"\x00\x12@\n\x08HistData\x12\x1b.routeguide.HistDataRequest\x1a\x15.routeguide.Dataframe\"\x00\x12@\n\x08TickData\x12\x1b.routeguide.TickDataRequest\x1a\x15.routeguide.Dataframe\"\x00\x12>\n\x0bStockBasics\x12\x16.routeguide.EmptyParam\x1a\x15.routeguide.Dataframe\"\x00\x12;\n\x08TodayAll\x12\x16.routeguide.EmptyParam\x1a\x15.routeguide.Dataframe\"\x00\x12\x44\n\nTodayTicks\x12\x1d.routeguide.TodayTicksRequest\x1a\x15.routeguide.Dataframe\"\x00\x12\x38\n\x05Index\x12\x16.routeguide.EmptyParam\x1a\x15.routeguide.Dataframe\"\x00\x42\x32\n\x18\x63n.pxsdirac.grpc.tushareB\x0eTushareServiceP\x01\xa2\x02\x03RTGb\x06proto3')
)

_KTYPE = _descriptor.EnumDescriptor(
  name='KType',
  full_name='routeguide.KType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='D', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='W', index=1, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='M', index=2, number=2,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='m5', index=3, number=3,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='m15', index=4, number=4,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='m30', index=5, number=5,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='m60', index=6, number=6,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=382,
  serialized_end=445,
)
_sym_db.RegisterEnumDescriptor(_KTYPE)

KType = enum_type_wrapper.EnumTypeWrapper(_KTYPE)
D = 0
W = 1
M = 2
m5 = 3
m15 = 4
m30 = 5
m60 = 6



_TODAYTICKSREQUEST = _descriptor.Descriptor(
  name='TodayTicksRequest',
  full_name='routeguide.TodayTicksRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='code', full_name='routeguide.TodayTicksRequest.code', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=29,
  serialized_end=62,
)


_EMPTYPARAM = _descriptor.Descriptor(
  name='EmptyParam',
  full_name='routeguide.EmptyParam',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=64,
  serialized_end=76,
)


_STRINGVALUE = _descriptor.Descriptor(
  name='StringValue',
  full_name='routeguide.StringValue',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='value', full_name='routeguide.StringValue.value', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=78,
  serialized_end=106,
)


_HISTDATAREQUEST = _descriptor.Descriptor(
  name='HistDataRequest',
  full_name='routeguide.HistDataRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='code', full_name='routeguide.HistDataRequest.code', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='start', full_name='routeguide.HistDataRequest.start', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='end', full_name='routeguide.HistDataRequest.end', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='kType', full_name='routeguide.HistDataRequest.kType', index=3,
      number=4, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=109,
  serialized_end=238,
)


_TICKDATAREQUEST = _descriptor.Descriptor(
  name='TickDataRequest',
  full_name='routeguide.TickDataRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='code', full_name='routeguide.TickDataRequest.code', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='date', full_name='routeguide.TickDataRequest.date', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=240,
  serialized_end=303,
)


_DATAFRAME = _descriptor.Descriptor(
  name='Dataframe',
  full_name='routeguide.Dataframe',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='json', full_name='routeguide.Dataframe.json', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=305,
  serialized_end=330,
)


_DATE = _descriptor.Descriptor(
  name='Date',
  full_name='routeguide.Date',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='year', full_name='routeguide.Date.year', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='month', full_name='routeguide.Date.month', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='day', full_name='routeguide.Date.day', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=332,
  serialized_end=380,
)

_HISTDATAREQUEST.fields_by_name['start'].message_type = _DATE
_HISTDATAREQUEST.fields_by_name['end'].message_type = _DATE
_HISTDATAREQUEST.fields_by_name['kType'].enum_type = _KTYPE
_TICKDATAREQUEST.fields_by_name['date'].message_type = _DATE
DESCRIPTOR.message_types_by_name['TodayTicksRequest'] = _TODAYTICKSREQUEST
DESCRIPTOR.message_types_by_name['EmptyParam'] = _EMPTYPARAM
DESCRIPTOR.message_types_by_name['StringValue'] = _STRINGVALUE
DESCRIPTOR.message_types_by_name['HistDataRequest'] = _HISTDATAREQUEST
DESCRIPTOR.message_types_by_name['TickDataRequest'] = _TICKDATAREQUEST
DESCRIPTOR.message_types_by_name['Dataframe'] = _DATAFRAME
DESCRIPTOR.message_types_by_name['Date'] = _DATE
DESCRIPTOR.enum_types_by_name['KType'] = _KTYPE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

TodayTicksRequest = _reflection.GeneratedProtocolMessageType('TodayTicksRequest', (_message.Message,), {
  'DESCRIPTOR' : _TODAYTICKSREQUEST,
  '__module__' : 'tushare_pb2'
  # @@protoc_insertion_point(class_scope:routeguide.TodayTicksRequest)
  })
_sym_db.RegisterMessage(TodayTicksRequest)

EmptyParam = _reflection.GeneratedProtocolMessageType('EmptyParam', (_message.Message,), {
  'DESCRIPTOR' : _EMPTYPARAM,
  '__module__' : 'tushare_pb2'
  # @@protoc_insertion_point(class_scope:routeguide.EmptyParam)
  })
_sym_db.RegisterMessage(EmptyParam)

StringValue = _reflection.GeneratedProtocolMessageType('StringValue', (_message.Message,), {
  'DESCRIPTOR' : _STRINGVALUE,
  '__module__' : 'tushare_pb2'
  # @@protoc_insertion_point(class_scope:routeguide.StringValue)
  })
_sym_db.RegisterMessage(StringValue)

HistDataRequest = _reflection.GeneratedProtocolMessageType('HistDataRequest', (_message.Message,), {
  'DESCRIPTOR' : _HISTDATAREQUEST,
  '__module__' : 'tushare_pb2'
  # @@protoc_insertion_point(class_scope:routeguide.HistDataRequest)
  })
_sym_db.RegisterMessage(HistDataRequest)

TickDataRequest = _reflection.GeneratedProtocolMessageType('TickDataRequest', (_message.Message,), {
  'DESCRIPTOR' : _TICKDATAREQUEST,
  '__module__' : 'tushare_pb2'
  # @@protoc_insertion_point(class_scope:routeguide.TickDataRequest)
  })
_sym_db.RegisterMessage(TickDataRequest)

Dataframe = _reflection.GeneratedProtocolMessageType('Dataframe', (_message.Message,), {
  'DESCRIPTOR' : _DATAFRAME,
  '__module__' : 'tushare_pb2'
  # @@protoc_insertion_point(class_scope:routeguide.Dataframe)
  })
_sym_db.RegisterMessage(Dataframe)

Date = _reflection.GeneratedProtocolMessageType('Date', (_message.Message,), {
  'DESCRIPTOR' : _DATE,
  '__module__' : 'tushare_pb2'
  # @@protoc_insertion_point(class_scope:routeguide.Date)
  })
_sym_db.RegisterMessage(Date)


DESCRIPTOR._options = None

_TUSHARESERVICE = _descriptor.ServiceDescriptor(
  name='TushareService',
  full_name='routeguide.TushareService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=448,
  serialized_end=913,
  methods=[
  _descriptor.MethodDescriptor(
    name='MoneySupply',
    full_name='routeguide.TushareService.MoneySupply',
    index=0,
    containing_service=None,
    input_type=_EMPTYPARAM,
    output_type=_DATAFRAME,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='HistData',
    full_name='routeguide.TushareService.HistData',
    index=1,
    containing_service=None,
    input_type=_HISTDATAREQUEST,
    output_type=_DATAFRAME,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='TickData',
    full_name='routeguide.TushareService.TickData',
    index=2,
    containing_service=None,
    input_type=_TICKDATAREQUEST,
    output_type=_DATAFRAME,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='StockBasics',
    full_name='routeguide.TushareService.StockBasics',
    index=3,
    containing_service=None,
    input_type=_EMPTYPARAM,
    output_type=_DATAFRAME,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='TodayAll',
    full_name='routeguide.TushareService.TodayAll',
    index=4,
    containing_service=None,
    input_type=_EMPTYPARAM,
    output_type=_DATAFRAME,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='TodayTicks',
    full_name='routeguide.TushareService.TodayTicks',
    index=5,
    containing_service=None,
    input_type=_TODAYTICKSREQUEST,
    output_type=_DATAFRAME,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='Index',
    full_name='routeguide.TushareService.Index',
    index=6,
    containing_service=None,
    input_type=_EMPTYPARAM,
    output_type=_DATAFRAME,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_TUSHARESERVICE)

DESCRIPTOR.services_by_name['TushareService'] = _TUSHARESERVICE

# @@protoc_insertion_point(module_scope)
